
import React from 'react';
import { AlertTriangle, Shield } from 'lucide-react';

const DisclaimerSection: React.FC = () => {
  return (
    <section className="py-24 relative overflow-hidden" id="disclaimer">
      {/* Background elements */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 right-0 w-full h-full cyber-grid"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 rounded-full bg-neon-pink/5 blur-3xl"></div>
      </div>
      
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <span className="inline-block py-1 px-3 rounded-full text-neon-purple text-xs font-semibold bg-neon-purple/10 mb-3 flex items-center justify-center mx-auto w-fit">
            <AlertTriangle className="h-3 w-3 mr-1" />
            LEGAL INFORMATION
          </span>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6">
            <span className="text-white">Legal </span>
            <span className="neon-text-purple">Disclaimer</span>
          </h2>
          <p className="max-w-2xl mx-auto text-white/70 text-lg">
            Please read this important information about the use of Name Insight Predictor.
          </p>
        </div>
        
        <div className="max-w-4xl mx-auto glass-panel rounded-lg p-8 border border-neon-purple/30 relative overflow-hidden">
          <Shield className="absolute -right-12 -bottom-12 h-48 w-48 text-neon-purple/10" />
          
          <div className="space-y-6 relative z-10">
            <div>
              <h3 className="text-xl font-cyber text-neon-purple mb-3">Informational Purpose Only</h3>
              <p className="text-white/70">
                Name Insight Predictor is provided for entertainment, educational, and informational purposes only. 
                The analyses, predictions, and insights generated by this tool should not be considered as professional 
                advice, scientific fact, or absolute truth. Users should exercise their own judgment when interpreting 
                and applying any information provided.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-cyber text-neon-purple mb-3">No Guarantees or Warranties</h3>
              <p className="text-white/70">
                AI WEB TOOLS LLC makes no guarantees, representations, or warranties of any kind regarding the accuracy, 
                completeness, reliability, or suitability of the information provided by Name Insight Predictor. The analyses 
                are based on patterns, historical data, and algorithms which have inherent limitations and may not accurately 
                reflect personal realities.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-cyber text-neon-purple mb-3">Not a Basis for Decisions</h3>
              <p className="text-white/70">
                Users should not make important personal, financial, legal, medical, or other significant decisions based 
                solely on information provided by Name Insight Predictor. The tool's outputs should be considered as one of 
                many perspectives and not as definitive guidance for life choices.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-cyber text-neon-purple mb-3">Limitation of Liability</h3>
              <p className="text-white/70">
                AI WEB TOOLS LLC and its affiliates, officers, employees, agents, partners, and licensors shall not be liable 
                for any direct, indirect, incidental, special, consequential, or punitive damages resulting from the use of, or 
                inability to use, Name Insight Predictor or any information provided through it.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-cyber text-neon-purple mb-3">Data Privacy</h3>
              <p className="text-white/70">
                By using Name Insight Predictor, you acknowledge that the names provided for analysis are processed according to 
                our Privacy Policy. While we prioritize data security, no method of electronic transmission or storage is 100% 
                secure, and we cannot guarantee absolute security.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-cyber text-neon-purple mb-3">User Responsibility</h3>
              <p className="text-white/70">
                By using Name Insight Predictor, you agree to use the service responsibly and ethically. The tool should not be 
                used to make determinations about others without their consent or to engage in discriminatory practices based on 
                name analysis.
              </p>
            </div>
            
            <div className="pt-4 border-t border-white/10">
              <p className="text-white/60 text-sm">
                By proceeding to use Name Insight Predictor, you acknowledge that you have read, understood, and agree to the terms 
                outlined in this disclaimer. If you do not agree with these terms, please discontinue use of the service immediately.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
